Repository anki-geo/ultimate-geography, pull requests merged in 2020-04, with the labels that each got.

#234 Change some strings in Spanish translation
  src/data.csv
Labels: content

#255 Document guidelines for every field
  CONTRIBUTING.md
Labels: chore

#258 Make maps of Balkans and Saint Helena consistent with main style
  sources.csv
  src/media/ug-map-balkan_peninsula.png
  src/media/ug-map-saint_helena.png
Labels: content

#274 Don't apply shadow to images with non-rectangular outlines
  sources.csv
  src/data.csv
  src/media/ug-flag-nepal-nobox.svg
  src/media/ug-map-africa-nobox.png
  src/media/ug-map-antarctica-nobox.png
  src/media/ug-map-arctic_ocean-nobox.png
  src/media/ug-map-asia-nobox.png
  src/media/ug-map-atlantic_ocean-nobox.png
  src/media/ug-map-europe-nobox.png
  src/media/ug-map-indian_ocean-nobox.png
  src/media/ug-map-north_america-nobox.png
  src/media/ug-map-oceania-nobox.png
  src/media/ug-map-pacific_ocean-nobox.png
  src/media/ug-map-south_africa-nobox.png
  src/media/ug-map-southern_ocean-nobox.jpg
  src/style.css
Labels: structure

#275 Improve map of Southern Ocean (slightly)
  sources.csv
  src/data.csv
  src/media/ug-map-southern_ocean-nobox.jpg
  src/media/ug-map-southern_ocean-nobox.png
Labels: content

#290 Improve night mode glow/shadow of flags
  src/style.css
Labels: structure

#296 Add CONTRIBUTING.md links
  CONTRIBUTING.md
Labels: chore
