Repository anki-geo/ultimate-geography, pull requests merged in 2022-04, with the labels that each got.

#536 Remove 'European_Union' tag from United Kingdom
  src/data/main.csv
Labels: structure

#531 Make miscellaneous flag changes
  sources.csv
  src/media/flags/ug-flag-afghanistan.png
  src/media/flags/ug-flag-afghanistan.svg
  src/media/flags/ug-flag-mauritania.svg
Labels: content

#538 Polish deck translation
  README.md
  recipes/legacy_csv_from_split_csvs.yaml
  recipes/legacy_csv_to_split_csvs.yaml
  recipes/source_to_anki.yaml
  src/data/capital.csv
  src/data/capital_hint.csv
  src/data/capital_info.csv
  src/data/country.csv
  src/data/country_info.csv
  src/data/flag_similarity.csv
  src/data/guid.csv
  src/headers/desc.html
Labels: translation
